// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWMSRHTkUYgQuqxjkxf2gCuIbaFWfPtJg',
    appId: '1:934816268434:android:51c638ef3b32b2abcd664b',
    messagingSenderId: '934816268434',
    projectId: 'wechat-d87fa',
    storageBucket: 'wechat-d87fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvgm9OA3907tLRaTqMZv_KVoUD5E9SU7g',
    appId: '1:934816268434:ios:a315c15d608ea186cd664b',
    messagingSenderId: '934816268434',
    projectId: 'wechat-d87fa',
    storageBucket: 'wechat-d87fa.appspot.com',
    androidClientId: '934816268434-meiv3ecaa86v32fci09qt2de74h5ctio.apps.googleusercontent.com',
    iosClientId: '934816268434-u8h5u084ot0a69vgvr7vdpuuu22blm9u.apps.googleusercontent.com',
    iosBundleId: 'com.wechat.weChat',
  );
}
